### ISSUE TITLE
What do you think about using `requestanimationframe`?

### ISSUE THREAD

**Issue by frederikhors** [svelte-drama/suspense#3]
Amazing work!

What do you think about using `requestanimationframe` when switching state to not block the main thread?

**Comment by WaltzingPenguin** [comment]
Status updates are already handled in a setTimeout block, chiefly to allow any subsequent promises to register.  How would `requestAnimationFrame` be a performance improvement?  It's certainly an abuse of the intended functionality.

**Comment by frederikhors** [comment]
`setTimeout` can block the main thread. https://developers.google.com/web/fundamentals/performance/rendering/optimize-javascript-execution

**Comment by WaltzingPenguin** [comment]
Anything can block the main thread, if you do dumb stuff inside of it.  That includes both setTimeout and requestAnimationFrame.

The article you linked does not actually back you up, so I'm marking this as "Won't Fix".  That stance would change of course, if there was a demo/benchmark provided that used this library and demonstrated some performance difference.
